project:
  type: website

website:
  title: "My Data Science Showcase"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Dashboard
      - href: shiny-apps.qmd
        text: Shiny Apps
      - href: shiny-live.qmd
        text: Shinylive

format:
  html:
    theme: cosmo
    toc: true